### ISSUE TITLE
Doesn't include phonetisaurus-g2p

### ISSUE THREAD

**Issue by BongoEADGC6** [mattcurrycom/RPI-Jasper-Dependencies#2]
After running the dependency installer and the client installer from the other repo, I get the following error:

```*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper-client/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper-client/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper-client/client/vocabcompiler.py", line 320, in _compile_dictionary
    g2pconverter = PhonetisaurusG2P(**PhonetisaurusG2P.get_config())
  File "/home/pi/jasper-client/client/g2p.py", line 90, in __new__
    "$PATH.")
OSError: Can't find command 'phonetisaurus-g2p'! Please check if Phonetisaurus is installed and in your $PATH.
```

**Comment by mattcurrycom** [comment]
It actually does, but there is a script to run when you use my image.  This is not meant to be ran alone.
